[build]
  functions = "netlify/functions"
  publish   = "frontend/dist"
  command   = "npm ci && npm --prefix frontend ci && npm --prefix frontend run build"

[build.environment]
  NODE_VERSION = "20"
